.PHONY: clean All

All:
	@echo "----------Building project:[ fundas - Debug ]----------"
	@cd "fundas" && "$(MAKE)" -f  "fundas.mk"
clean:
	@echo "----------Cleaning project:[ fundas - Debug ]----------"
	@cd "fundas" && "$(MAKE)" -f  "fundas.mk" clean
