.PHONY: clean All

All:
	@echo "----------Building project:[ fromTemplate - Debug ]----------"
	@cd "fromTemplate" && "$(MAKE)" -f  "fromTemplate.mk"
clean:
	@echo "----------Cleaning project:[ fromTemplate - Debug ]----------"
	@cd "fromTemplate" && "$(MAKE)" -f  "fromTemplate.mk" clean
